### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Toricane** [JUGADOR123/Paginator.py#1]
I got this on line 21 of Paginator.py:
`pages: list[discord.Embed],`
The only way I got it to work was to remove the type hinting for `pages`.

**Comment by Toricane** [comment]
1. Copy pasted Paginator.py into a file on my bot named `paginator2`
2. `from paginator2 import Paginator`
3. ```py
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/KAHBAM/cogs/history.py", line 8, in <module>
    from paginator2 import Paginator
  File "/home/runner/KAHBAM/paginator2.py", line 21, in <module>
    pages: list[discord.Embed],
TypeError: 'type' object is not subscriptable
```

**Comment by JUGADOR123** [comment]
already fixed it on my end
